services:
    marttiphpbb.stopforumspamreport.listener:
        class: marttiphpbb\stopforumspamreport\event\listener
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @log
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }
